#!/usr/bin/env python3
"""
fujitsu_tx.py - interactive IR transmitter for the captured Fujitsu-family A/C protocol.

No external Python packages required.

It uses analysis.json produced by acir.py as the protocol database:
  * baseline full-state packet
  * temperature variants
  * mode variants
  * fan variants
  * swing variants
  * short OFF packet
  * checksum suffix start

The 38 kHz carrier is generated by Linux PWM. Python only gates PWM on/off
for MARK/SPACE durations.

Expected Luckfox wiring used during development:

    3.3 V ---- IR LED ---- 100R ---- 100R ---- GPIO1_C5 / PWM9_M1

PWM disabled -> GPIO HIGH -> LED OFF
PWM enabled  -> inverted ~38 kHz waveform -> LED emits carrier bursts
"""

import argparse
import gc
import json
import os
import sys
import time
from pathlib import Path


# ---------------------------------------------------------------------------
# PWM / measured protocol timing
# ---------------------------------------------------------------------------

DEFAULT_PWMCHIP = Path("/sys/class/pwm/pwmchip9")
DEFAULT_CHANNEL = 0

# 38 kHz: 1 / 38000 s ~= 26.3158 us
PWM_PERIOD_NS = 26_316
PWM_DUTY_NS = 8_772       # ~33.3% optical/carrier duty with our inverted setup

# Timings measured from the original remote captures.
# They are intentionally easy to edit after checking the synthesized waveform
# with ATK-Logic.
HEADER_MARK_US = 3_260
HEADER_SPACE_US = 1_635
BIT_MARK_US = 410
ZERO_SPACE_US = 430
ONE_SPACE_US = 1_215
TRAILER_MARK_US = 410

# Optional software compensation for sysfs transition latency.
# Leave at 0 initially. If ATK-Logic shows every MARK is e.g. ~35 us too long,
# try MARK_COMPENSATION_US=35. Same idea for spaces.
MARK_COMPENSATION_US = 0
SPACE_COMPENSATION_US = 0


# ---------------------------------------------------------------------------
# Protocol database loader / packet constructor
# ---------------------------------------------------------------------------

def _experiment(db, name):
    for e in db.get("experiments", []):
        if e.get("name") == name:
            return e
    raise ValueError(f"analysis.json has no experiment named {name!r}")


def _packet_from_entry(entry):
    text = entry.get("packet_lsb_hex")
    if not text:
        raise ValueError("experiment entry has no packet_lsb_hex")
    return bytearray.fromhex(text)


class ProtocolDB:
    def __init__(self, path):
        self.path = Path(path)
        with self.path.open("r", encoding="utf-8") as f:
            self.db = json.load(f)

        baseline_exp = _experiment(self.db, "baseline_repeat")
        baseline_entries = baseline_exp.get("entries", [])
        if not baseline_entries:
            raise ValueError("baseline_repeat contains no entries")

        self.baseline_entry = baseline_entries[0]
        self.baseline_state = dict(self.baseline_entry["state"])
        self.baseline = _packet_from_entry(self.baseline_entry)
        self.full_len = len(self.baseline)

        if self.full_len < 2:
            raise ValueError("baseline packet is implausibly short")

        self.checksum_index = self.full_len - 1
        self.checksum_start = self._find_checksum_start()

        self.field_maps = {}
        self.field_masks = {}
        for experiment_name, state_field in (
            ("temperature", "temperature_c"),
            ("mode", "mode"),
            ("fan", "fan"),
            ("swing", "swing"),
        ):
            self.field_maps[state_field] = self._build_field_map(
                experiment_name, state_field
            )

        power_exp = _experiment(self.db, "power_off")
        off_entries = power_exp.get("entries", [])
        if not off_entries:
            raise ValueError("power_off contains no entries")
        self.off_packet = bytes(_packet_from_entry(off_entries[0]))

    def _find_checksum_start(self):
        frame_lengths = self.db.get("frame_lengths", {})
        info = frame_lengths.get(str(self.full_len), {})
        starts = info.get("zero_sum_suffix_starts", [])
        if starts:
            return int(starts[0])

        # Known from our captured dataset, but only used as fallback.
        return 7

    def _build_field_map(self, experiment_name, state_field):
        exp = _experiment(self.db, experiment_name)
        mapping = {}

        for entry in exp.get("entries", []):
            state = entry.get("state", {})
            if state_field not in state:
                continue

            packet = _packet_from_entry(entry)
            if len(packet) != self.full_len:
                # Preserve bad/short captures in the dataset, but never use one
                # as a full-state synthesis source.
                continue

            # A valid full-state capture keeps the canonical header through
            # checksum_start (byte 7 in our captures). This filters accidental
            # one-bit-shift decodes such as the earlier bad 22 C sample.
            header_end = self.checksum_start + 1
            if packet[:header_end] != self.baseline[:header_end]:
                continue

            mapping[state[state_field]] = bytes(packet)

        if not mapping:
            raise ValueError(
                f"no valid {self.full_len}-byte entries for {state_field!r}"
            )

        # Infer exactly which BITS belong to this controlled field.
        # This matters because fan and swing both live in byte 10.
        masks = bytearray(self.full_len)
        for variant in mapping.values():
            for i in range(self.checksum_index):
                masks[i] |= self.baseline[i] ^ variant[i]

        self.field_masks[state_field] = bytes(masks)
        return mapping

    def choices(self, field):
        values = list(self.field_maps[field].keys())
        if field == "temperature_c":
            return sorted(values, key=int)
        return values

    def _apply_variant(self, packet, variant, field):
        """
        Apply only the bits controlled by this field.

        Controlled experiments let us infer masks independently, e.g.:
          fan   -> byte 10 bits 0..2
          swing -> byte 10 bit 4

        Thus fan + swing can safely share the same byte.
        """
        masks = self.field_masks[field]
        for i in range(self.checksum_index):
            mask = masks[i]
            if mask:
                packet[i] = (packet[i] & (~mask & 0xFF)) | (variant[i] & mask)

    def build_on(self, temperature_c, mode, fan, swing):
        selected = {
            "temperature_c": temperature_c,
            "mode": mode,
            "fan": fan,
            "swing": swing,
        }

        packet = bytearray(self.baseline)

        for field, value in selected.items():
            try:
                variant = self.field_maps[field][value]
            except KeyError:
                choices = ", ".join(map(str, self.choices(field)))
                raise ValueError(
                    f"no captured mapping for {field}={value!r}; "
                    f"available: {choices}"
                )
            self._apply_variant(packet, variant, field)

        # Captures show sum(packet[checksum_start:]) == 0 mod 256.
        packet[self.checksum_index] = (
            -sum(packet[self.checksum_start:self.checksum_index])
        ) & 0xFF

        if sum(packet[self.checksum_start:]) & 0xFF:
            raise AssertionError("internal checksum construction failure")

        return bytes(packet)

    def build(self, power, temperature_c=None, mode=None, fan=None, swing=None):
        if power == "off":
            return self.off_packet

        return self.build_on(
            temperature_c=temperature_c,
            mode=mode,
            fan=fan,
            swing=swing,
        )


# ---------------------------------------------------------------------------
# PWM control
# ---------------------------------------------------------------------------

def _write_text(path, value):
    Path(path).write_text(str(value), encoding="ascii")


def ensure_pwm_exported(chip, channel):
    chip = Path(chip)
    pwm = chip / f"pwm{channel}"

    if not chip.exists():
        raise RuntimeError(f"PWM chip does not exist: {chip}")

    if not pwm.exists():
        try:
            _write_text(chip / "export", channel)
        except OSError as e:
            # It may already be exported but sysfs hasn't populated the path yet.
            if not pwm.exists():
                raise RuntimeError(f"could not export PWM channel: {e}") from e

        deadline = time.monotonic() + 1.0
        while not pwm.exists() and time.monotonic() < deadline:
            time.sleep(0.01)

    if not pwm.exists():
        raise RuntimeError(f"PWM path did not appear: {pwm}")

    return pwm


class PWMGate:
    def __init__(self, chip, channel):
        self.chip = Path(chip)
        self.channel = int(channel)
        self.pwm = ensure_pwm_exported(self.chip, self.channel)
        self.enable_path = self.pwm / "enable"
        self.fd = None

    def configure(self):
        # Must disable before changing period/duty on most PWM drivers.
        try:
            _write_text(self.enable_path, 0)
        except OSError:
            pass

        _write_text(self.pwm / "period", PWM_PERIOD_NS)
        _write_text(self.pwm / "duty_cycle", PWM_DUTY_NS)

        polarity_path = self.pwm / "polarity"
        if polarity_path.exists():
            polarity = polarity_path.read_text(encoding="ascii").strip()
            print(f"PWM polarity: {polarity}")
            if polarity != "inversed":
                print(
                    "WARNING: this setup was tested with polarity='inversed'.\n"
                    "         Verify LED-off level and optical duty before transmitting.",
                    file=sys.stderr,
                )

        _write_text(self.enable_path, 0)

        # Keep one descriptor open. pwrite() lets every write target offset 0
        # without open()/close()/seek() on every ~400 us transition.
        self.fd = os.open(self.enable_path, os.O_WRONLY)

    def set(self, enabled):
        if self.fd is None:
            raise RuntimeError("PWMGate.configure() has not been called")
        os.pwrite(self.fd, b"1" if enabled else b"0", 0)

    def off(self):
        if self.fd is not None:
            try:
                self.set(False)
            except OSError:
                pass
        else:
            try:
                _write_text(self.enable_path, 0)
            except OSError:
                pass

    def close(self):
        self.off()
        if self.fd is not None:
            os.close(self.fd)
            self.fd = None


# ---------------------------------------------------------------------------
# IR waveform generation
# ---------------------------------------------------------------------------

def packet_bits_lsb_first(packet):
    for byte in packet:
        for bit in range(8):
            yield (byte >> bit) & 1


def waveform_for_packet(packet):
    """
    Return [(is_mark, duration_us), ...].

    Captured protocol:
      header  ~3260 mark, 1635 space
      bit     ~410 mark, then 430 space for 0 / 1215 space for 1
      trailer ~410 mark
    """
    wave = [
        (True, HEADER_MARK_US),
        (False, HEADER_SPACE_US),
    ]

    for bit in packet_bits_lsb_first(packet):
        wave.append((True, BIT_MARK_US))
        wave.append((False, ONE_SPACE_US if bit else ZERO_SPACE_US))

    wave.append((True, TRAILER_MARK_US))
    return wave


def _busy_wait_until(deadline_ns):
    # Do not call sleep() for sub-millisecond protocol timing.
    while time.monotonic_ns() < deadline_ns:
        pass


def try_realtime():
    """
    Best effort only. Usually succeeds when run as root on the Luckfox.
    SCHED_FIFO reduces the chance of Linux preempting Python in a 400 us pulse.
    """
    try:
        os.sched_setscheduler(0, os.SCHED_FIFO, os.sched_param(50))
        print("Scheduler: SCHED_FIFO priority 50")
        return True
    except (AttributeError, PermissionError, OSError) as e:
        print(f"Scheduler: normal ({e})")
        return False


def transmit(gate, packet, repeats=1, repeat_gap_ms=25.0, realtime=True):
    wave = waveform_for_packet(packet)

    if realtime:
        try_realtime()

    gc_was_enabled = gc.isenabled()
    gc.disable()

    try:
        gate.off()

        for repeat in range(repeats):
            for is_mark, duration_us in wave:
                compensated = duration_us
                if is_mark:
                    compensated = max(1, duration_us - MARK_COMPENSATION_US)
                else:
                    compensated = max(1, duration_us - SPACE_COMPENSATION_US)

                # Record the start before the sysfs write. This means time spent
                # performing the transition is included in the requested slot,
                # which generally gives less accumulated stretch than starting
                # the timer after write() returns.
                start = time.monotonic_ns()
                gate.set(is_mark)
                deadline = start + int(compensated * 1000)
                _busy_wait_until(deadline)

            gate.off()

            if repeat + 1 < repeats:
                time.sleep(repeat_gap_ms / 1000.0)

    finally:
        gate.off()
        if gc_was_enabled:
            gc.enable()


# ---------------------------------------------------------------------------
# Interactive UI
# ---------------------------------------------------------------------------

def packet_hex(packet):
    return " ".join(f"{x:02X}" for x in packet)


def prompt_choice(label, values, default):
    values = list(values)

    while True:
        print(f"\n{label}:")
        for i, value in enumerate(values, 1):
            marker = "  [default]" if value == default else ""
            print(f"  {i:2d}) {value}{marker}")

        raw = input(f"{label} [{default}]: ").strip()
        if not raw:
            return default

        if raw.isdigit():
            idx = int(raw)
            if 1 <= idx <= len(values):
                return values[idx - 1]

        for value in values:
            if str(value).lower() == raw.lower():
                return value

        print("Invalid choice.")


def interactive(db, gate, repeats):
    state = {
        "power": "on",
        "temperature_c": db.baseline_state.get(
            "temperature_c", db.choices("temperature_c")[0]
        ),
        "mode": db.baseline_state.get("mode", db.choices("mode")[0]),
        "fan": db.baseline_state.get("fan", db.choices("fan")[0]),
        "swing": db.baseline_state.get("swing", db.choices("swing")[0]),
    }

    while True:
        print("\n" + "=" * 68)
        print("FUJITSU A/C IR TRANSMITTER")
        print("=" * 68)

        state["power"] = prompt_choice("Power", ["on", "off"], state["power"])

        if state["power"] == "on":
            state["mode"] = prompt_choice(
                "Mode", db.choices("mode"), state["mode"]
            )
            state["temperature_c"] = prompt_choice(
                "Temperature C",
                db.choices("temperature_c"),
                state["temperature_c"],
            )
            state["fan"] = prompt_choice(
                "Fan", db.choices("fan"), state["fan"]
            )
            state["swing"] = prompt_choice(
                "Swing", db.choices("swing"), state["swing"]
            )

            packet = db.build_on(
                state["temperature_c"],
                state["mode"],
                state["fan"],
                state["swing"],
            )

            print("\nConstructed full-state packet:")
            print(f"  power       = on")
            print(f"  mode        = {state['mode']}")
            print(f"  temperature = {state['temperature_c']} C")
            print(f"  fan         = {state['fan']}")
            print(f"  swing       = {state['swing']}")
        else:
            packet = db.off_packet
            print("\nConstructed OFF packet:")

        print(f"\n  {packet_hex(packet)}")
        print(f"  {len(packet)} bytes / {len(packet) * 8} bits")

        while True:
            raw = input(
                "\n[T]ransmit, [E]dit state, [Q]uit"
                " (Enter = transmit): "
            ).strip().lower()

            if raw in ("", "t", "transmit"):
                print("Transmitting...")
                transmit(gate, packet, repeats=repeats)
                print("Done. PWM is OFF.")
                continue

            if raw in ("e", "edit"):
                break

            if raw in ("q", "quit"):
                return

            print("Unknown command.")


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description="Interactive Fujitsu A/C IR transmitter using analysis.json + PWM"
    )
    parser.add_argument(
        "analysis",
        nargs="?",
        default="analysis.json",
        help="machine-readable analysis.json from acir.py (default: ./analysis.json)",
    )
    parser.add_argument(
        "--pwmchip",
        default=str(DEFAULT_PWMCHIP),
        help=f"PWM chip sysfs path (default: {DEFAULT_PWMCHIP})",
    )
    parser.add_argument(
        "--channel",
        type=int,
        default=DEFAULT_CHANNEL,
        help=f"PWM channel inside pwmchip (default: {DEFAULT_CHANNEL})",
    )
    parser.add_argument(
        "--repeats",
        type=int,
        default=1,
        help="number of complete frames per transmission (default: 1)",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="load protocol database and construct packets, but do not touch PWM",
    )
    args = parser.parse_args()

    db = ProtocolDB(args.analysis)

    print(f"Loaded: {Path(args.analysis).resolve()}")
    print(f"Baseline: {packet_hex(db.baseline)}")
    print(f"OFF:      {packet_hex(db.off_packet)}")
    print(f"Checksum: zero-sum suffix starting at byte {db.checksum_start}")
    print(
        "Choices: "
        f"{len(db.choices('temperature_c'))} temperatures, "
        f"{len(db.choices('mode'))} modes, "
        f"{len(db.choices('fan'))} fan modes, "
        f"{len(db.choices('swing'))} swing states"
    )

    if args.dry_run:
        # Still use the normal interactive packet builder, but with a fake gate
        # that prints instead of touching hardware.
        class DryGate:
            def off(self):
                pass
            def set(self, enabled):
                pass

        # Override transmit in the least surprising way: let user build packets,
        # but warn that pressing T does not emit IR.
        global transmit
        real_transmit = transmit

        def dry_transmit(gate, packet, repeats=1, **kwargs):
            wave = waveform_for_packet(packet)
            total_us = sum(duration for _, duration in wave)
            print(
                f"DRY RUN: would send {len(packet)} bytes, "
                f"{len(wave)} mark/space slots, ~{total_us / 1000:.2f} ms"
            )

        transmit = dry_transmit
        try:
            interactive(db, DryGate(), args.repeats)
        finally:
            transmit = real_transmit
        return

    gate = PWMGate(args.pwmchip, args.channel)

    try:
        gate.configure()
        print(
            f"PWM configured: period={PWM_PERIOD_NS} ns, "
            f"duty={PWM_DUTY_NS} ns (~38 kHz)"
        )
        interactive(db, gate, args.repeats)
    finally:
        gate.close()


if __name__ == "__main__":
    main()
